title: devlooper
subtitle: Personal Blog
description: My personal blog about programming in English and Uzbek.
url: ''
baseurl: ''
urls:
  - text: About
    url: /about
  - text: Blog
    url: /blog
author_logo: profile.png
author: Mamur Djuraev
author_bio: 'Hi, my name is Mamur.'
author_email: mamurdjuraev@gmail.com
author_location: South Korea
typewrite-text: '!false - it''s funny because it''s true.'
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: 'https://google.com'
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: 'https://microsoft.com'
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: true
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: 'https://mit.org'
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: false
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - null
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
